### ISSUE TITLE
Missing htaccess

### ISSUE THREAD

**Issue by oleteacher** [jakepetty/php-login-example#1]
Great little script and would like to use in classroom project.

Do not have composer installed (cannot even use from school network - crazy, I know). Manually  changed header/footer for vendor files.

Now seem to need a .htaccess as links to login/register/etc do not work. Do you have a copy of it?

Thanks in advance.

**Comment by jakepetty** [comment]
Thanks for bringing this to my attention, the .htaccess file wasn't needed. The problem should be resolved in the latest commit.

4155638e13936b9d04c9d37d058fc5116767b250

**Comment by oleteacher** [comment]
Works perfectly. Did not think about being in subdirectory, Was focused on needing htaccess file.

Thank you!
